id: AB2015A51
title: Prayer to the Supremely Learned Holders of the Glorious Sakya Teachings
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:38:35.610057
  last_modified_at: 2022-03-01 05:38:35.610061
