id: AB2015A51
title: Aspiration to Follow the Gurus of the Ngor Tradition
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:38:35.607048
  last_modified_at: 2022-03-01 05:38:35.607056
